packages:
  - packages/server
  - packages/cli
  - '!**/test/**'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - yarn

shamefullyHoist: false
